apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-volume-grg
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/var/www/html/"
    